apiVersion: batch/v1
kind: Job
metadata:
  name: dsp-clone-job-test-codegen-gitops
spec:  
  template:         
    metadata:
      name: dsp-clone-job-test-codegen-gitops
    spec:  
      serviceAccountName: test-codegen-dsp-job
      containers:
      - name: initialize-dsp
        image: quay.io/redhat-ai-dev/utils:latest
        command:
        - /bin/bash
        - -c
        - |
          NS=$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace)
          oc wait -l statefulset=test-codegen-notebook --for=condition=ready pod --timeout=300s
          oc exec  StatefulSet/test-codegen-notebook -- git clone https://github.com/fpetk/test-codegen-helm
      restartPolicy: Never