apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: test-codegen
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/tpetkos/test-codegen-helm:f2019a07b74820e19052fef32665640e26e3bcf2@sha256:b91da24d36d1e7544dc120952db22a74c6067e268488d90be5a9278430e917ef # use pre-built to bootstrap 
          name: app-inference
